// GENERATED by tools/game/build_game_data.py — DO NOT EDIT BY HAND.
// Source of truth: tools/characters.json (character registry).
window.SU_DATA = {
  "generated": "2026-06-11T22:16:35Z",
  "source": "tools/characters.json via character_registry",
  "champions": [
    {
      "key": "vigolas",
      "shortcut": "v",
      "name": "Vigolas",
      "color": "#00ff88",
      "lineage": "VIKTOR-1",
      "role": "",
      "realm": "",
      "playable": false
    },
    {
      "key": "rougeina",
      "shortcut": "r",
      "name": "Rougeina",
      "color": "#ff3366",
      "lineage": "VIKTOR-6",
      "role": "",
      "realm": "",
      "playable": false
    },
    {
      "key": "kompis",
      "shortcut": "k",
      "name": "Kompis",
      "color": "#ffaa00",
      "lineage": "VIKTOR-3",
      "role": "",
      "realm": "",
      "playable": true
    },
    {
      "key": "smurjan",
      "shortcut": "s",
      "name": "Smurjan",
      "color": "#00aaff",
      "lineage": "RONNKVIST-8",
      "role": "",
      "realm": "",
      "playable": false
    },
    {
      "key": "trollmage",
      "shortcut": "t",
      "name": "Trollmage",
      "color": "#9933ff",
      "lineage": "VIKTOR-4",
      "role": "",
      "realm": "",
      "playable": false
    }
  ],
  "lineage": [
    {
      "key": "isa",
      "shortcut": "i",
      "name": "Isa",
      "color": "#67e8f9",
      "lineage": "VIKTOR-2",
      "role": "The Stillborn Heartbeat",
      "realm": "Helios-Heartbeat border",
      "playable": false
    },
    {
      "key": "viggeclips",
      "shortcut": "c",
      "name": "Viggeclips",
      "color": "#888888",
      "lineage": "CREATOR",
      "role": "The Author Channel",
      "realm": "",
      "playable": false
    },
    {
      "key": "opha",
      "shortcut": "o",
      "name": "Opha",
      "color": "#d946ef",
      "lineage": "VIKTOR-5",
      "role": "The Conjunction",
      "realm": "Astralis-Codexia border — the Dawnstar",
      "playable": false
    },
    {
      "key": "runa",
      "shortcut": "u",
      "name": "Runa",
      "color": "#d4a056",
      "lineage": "RONNKVIST-1",
      "role": "The First Rune-Speaker",
      "realm": "Ferdinand — inside the cork oak himself",
      "playable": false
    },
    {
      "key": "ogar",
      "shortcut": "g",
      "name": "Ögar",
      "color": "#a78bfa",
      "lineage": "RONNKVIST-2",
      "role": "The Far-Eye Watcher",
      "realm": "Thanatos — the Pillar of Names",
      "playable": false
    },
    {
      "key": "niva",
      "shortcut": "n",
      "name": "Niva",
      "color": "#e5e7eb",
      "lineage": "RONNKVIST-3",
      "role": "The Untraversed",
      "realm": "NULL — the first to survive it",
      "playable": false
    },
    {
      "key": "njord",
      "shortcut": "j",
      "name": "Njord",
      "color": "#38bdf8",
      "lineage": "RONNKVIST-4",
      "role": "The Tide-Reader",
      "realm": "Heartbeat — Tidekant, eastern shore of Buddy's Lake",
      "playable": false
    },
    {
      "key": "kvar",
      "shortcut": "q",
      "name": "Kvar",
      "color": "#c2675a",
      "lineage": "RONNKVIST-5",
      "role": "The Last One",
      "realm": "any — wherever the last one standing is",
      "playable": false
    },
    {
      "key": "vidar",
      "shortcut": "d",
      "name": "Vidar",
      "color": "#cdb878",
      "lineage": "RONNKVIST-6",
      "role": "The Silent Reckoner",
      "realm": "VOID-II — the rim of the Architects' Chamber",
      "playable": false
    },
    {
      "key": "iska",
      "shortcut": "a",
      "name": "Iska",
      "color": "#fbbf24",
      "lineage": "RONNKVIST-7",
      "role": "The Spark-Carrier",
      "realm": "LUMEN — the white-gold heartbeat-light altar",
      "playable": false
    },
    {
      "key": "tova",
      "shortcut": "w",
      "name": "Tova",
      "color": "#f59e0b",
      "lineage": "RONNKVIST-9",
      "role": "The Thunder-Herald",
      "realm": "all twelve realms — a gate in each",
      "playable": false
    }
  ],
  "total_souls": 16
};
